<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sand Creek Whitetail - Premium Hunting Experiences</title>
    <meta name="description" content="Experience the hunt of a lifetime with Sand Creek Whitetail. Trophy bucks, comfortable lodging, and expert guides in [Your Location].">
    <meta name="keywords" content="whitetail hunting, trophy bucks, hunting lodge, guided hunts, [Your Location]">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <style>
        /* CSS styles here (as in the previous example) */
        /* ... */
    </style>
</head>
<body>
    <header>
        <div class="container">
            <div id="branding">
                <h1><span class="highlight">Sand Creek</span> Whitetail</h1>
            </div>
            <nav>
                <ul>
                    <li class="current"><a href="index.html">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="hunts.html">Hunts</a></li>
                    <li><a href="gallery.html">Gallery</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <section id="showcase">
        <div class="container">
            <h1>Experience the Hunt of a Lifetime</h1>
            <p>Sand Creek Whitetail offers premium hunting experiences in [Your Location]</p>
            <a href="book-now.html" class="cta-button">Book Your Hunt</a>
        </div>
    </section>

    <section id="features">
        <div class="container">
            <h2>Why Choose Sand Creek Whitetail?</h2>
            <div class="feature">
                <img src="trophy-buck.jpg" alt="Trophy Buck">
                <h3>Trophy Bucks</h3>
                <p>Our carefully managed property consistently produces some of the biggest bucks in [Your Region].</p>
            </div>
            <div class="feature">
                <img src="luxury-lodge.jpg" alt="Luxury Lodge">
                <h3>Luxury Accommodations</h3>
                <p>Relax in our state-of-the-art lodge with all the comforts of home and then some.</p>
            </div>
            <div class="feature">
                <img src="expert-guide.jpg" alt="Expert Guide">
                <h3>Expert Guides</h3>
                <p>Our experienced guides know every inch of the property and will help ensure your success.</p>
            </div>
        </div>
    </section>

    <section id="testimonials">
        <div class="container">
            <h2>What Our Hunters Say</h2>
            <div class="testimonial">
                <img src="hunter1.jpg" alt="Happy Hunter">
                <blockquote>
                    "The best hunting experience of my life. I'll be back next season for sure!"
                </blockquote>
                <cite>- John D., Texas</cite>
            </div>
            <div class="testimonial">
                <img src="hunter2.jpg" alt="Satisfied Client">
                <blockquote>
                    "Top-notch guides and incredible deer. Sand Creek is the real deal."
                </blockquote>
                <cite>- Sarah M., Ohio</cite>
            </div>
        </div>
    </section>

    <section id="newsletter">
        <div class="container">
            <h2>Stay Updated on Prime Hunting Opportunities</h2>
            <p>Subscribe to our newsletter for exclusive offers and hunting tips.</p>
            <form id="newsletter-form">
                <input type="email" name="email" placeholder="Enter your email" required>
                <button type="submit" class="button_1">Subscribe</button>
            </form>
        </div>
    </section>

    <section id="photo-gallery">
        <div class="container">
            <h2>Recent Trophies</h2>
            <div class="gallery">
                <img src="trophy1.jpg" alt="Recent Trophy 1">
                <img src="trophy2.jpg" alt="Recent Trophy 2">
                <img src="trophy3.jpg" alt="Recent Trophy 3">
                <img src="trophy4.jpg" alt="Recent Trophy 4">
            </div>
            <a href="gallery.html" class="view-more">View Full Gallery</a>
        </div>
    </section>

    <section id="contact-info">
        <div class="container">
            <h2>Contact Us</h2>
            <p>Ready to book your hunt or have questions? Get in touch with us:</p>
            <ul>
                <li>Phone: (555) 123-4567</li>
                <li>Email: info@sandcreekwhitetail.com</li>
                <li>Address: 123 Hunting Lane, Deerville, State 12345</li>
            </ul>
        </div>
    </section>

    <footer>
        <div class="container">
            <p>&copy; 2025 Sand Creek Whitetail. All rights reserved.</p>
            <nav>
                <ul>
                    <li><a href="privacy-policy.html">Privacy Policy</a></li>
                    <li><a href="terms-of-service.html">Terms of Service</a></li>
                    <li><a href="sitemap.html">Sitemap</a></li>
                </ul>
            </nav>
            <div class="social-media">
                <a href="#" target="_blank"><img src="facebook-icon.png" alt="Facebook"></a>
                <a href="#" target="_blank"><img src="instagram-icon.png" alt="Instagram"></a>
                <a href="#" target="_blank"><img src="youtube-icon.png" alt="YouTube"></a>
            </div>
        </div>
    </footer>
</body>
</html>
