<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sand Creek Whitetail</title>
    <style>
        :root {
            --primary-color: #4A5D23;
            --secondary-color: #718C3A;
            --accent-color: #8FA54F;
            --background-color: #F0F0F0;
            --text-color: #333333;
        }

        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: var(--text-color);
            background-color: var(--background-color);
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
        }

        header {
            background-color: var(--primary-color);
            color: #ffffff;
            padding-top: 30px;
            min-height: 70px;
            border-bottom: var(--secondary-color) 3px solid;
        }

        header a {
            color: #ffffff;
            text-decoration: none;
            text-transform: uppercase;
            font-size: 16px;
        }

        header ul {
            padding: 0;
            margin: 0;
            list-style: none;
            overflow: hidden;
        }

        header li {
            float: left;
            display: inline;
            padding: 0 20px 0 20px;
        }

        header #branding {
            float: left;
        }

        header #branding h1 {
            margin: 0;
        }

        header nav {
            float: right;
            margin-top: 10px;
        }

        header .highlight, header .current a {
            color: var(--accent-color);
            font-weight: bold;
        }

        header a:hover {
            color: var(--secondary-color);
        }

        #showcase {
            min-height: 400px;
            background: url('showcase.jpg') no-repeat 0 -400px;
            text-align: center;
            color: #ffffff;
        }

        #showcase h1 {
            margin-top: 100px;
            font-size: 55px;
            margin-bottom: 10px;
        }

        #showcase p {
            font-size: 20px;
        }

        #newsletter {
            padding: 15px;
            color: #ffffff;
            background: var(--secondary-color);
        }

        #newsletter h1 {
            float: left;
        }

        #newsletter form {
            float: right;
            margin-top: 15px;
        }

        #newsletter input[type="email"] {
            padding: 4px;
            height: 25px;
            width: 250px;
        }

        .button_1 {
            height: 38px;
            background: var(--accent-color);
            border: 0;
            padding-left: 20px;
            padding-right: 20px;
            color: #ffffff;
        }

        #boxes {
            margin-top: 20px;
        }

        #boxes .box {
            float: left;
            text-align: center;
            width: 30%;
            padding: 10px;
        }

        #boxes .box img {
            width: 90px;
        }

        footer {
            padding: 20px;
            margin-top: 20px;
            color: #ffffff;
            background-color: var(--primary-color);
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <div id="branding">
                <h1><span class="highlight">Sand Creek</span> Whitetail</h1>
            </div>
            <nav>
                <ul>
                    <li class="current"><a href="index.html">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="hunts.html">Hunts</a></li>
                    <li><a href="gallery.html">Gallery</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <section id="showcase">
        <div class="container">
            <h1>Experience the Hunt of a Lifetime</h1>
            <p>Sand Creek Whitetail offers premium hunting experiences in [Your Location]</p>
        </div>
    </section>

    <section id="newsletter">
        <div class="container">
            <h1>Subscribe to Our Newsletter</h1>
            <form>
                <input type="email" placeholder="Enter Email...">
                <button type="submit" class="button_1">Subscribe</button>
            </form>
        </div>
    </section>

    <section id="boxes">
        <div class="container">
            <div class="box">
                <img src="trophy.png" alt="Trophy Buck">
                <h3>Trophy Bucks</h3>
                <p>Our property is home to some of the biggest bucks in the region.</p>
            </div>
            <div class="box">
                <img src="lodge.png" alt="Comfortable Lodging">
                <h3>Comfortable Lodging</h3>
                <p>Stay in our fully equipped, modern hunting lodge during your trip.</p>
            </div>
            <div class="box">
                <img src="guide.png" alt="Experienced Guides">
                <h3>Experienced Guides</h3>
                <p>Our knowledgeable guides ensure a safe and successful hunt.</p>
            </div>
        </div>
    </section>

    <footer>
        <p>Sand Creek Whitetail, Copyright &copy; 2025</p>
    </footer>
</body>
</html>
